package dsa.catalogueOrder.foundation.string;

import java.util.Scanner;

public class StringPermutationsIterative {
    public static void main(String[] args) {
        Scanner s = new Scanner(System.in);

        String input = s.next();

        printPermutationsIteratively(input);
    }

    private static int factorial(int n) {
        int fact = 1;
        for (int i = n; i >= 1; i--)
            fact *= i;
        return fact;
    }

    private static void printPermutationsIteratively(String input) {
        // factorial of input.length() is the number of permutations that would be generated by any given string.
        int fact = factorial(input.length());
        for (int i = 0; i < fact; i++) {
            int temp = i;
            StringBuilder sb = new StringBuilder(input);
            for (int j = input.length(); j >= 1; j--) {
                int div = temp / j;
                int rem = temp % j;

                System.out.print(sb.charAt(rem));
                sb.deleteCharAt(rem);
                temp = div;
            }
            System.out.println();
        }
    }
}
